### ISSUE TITLE
[Feature Request] Allow tracker to display all shuffled entrances

### ISSUE THREAD

**Issue by SuperBro64** [SuperDude88/TWWHD-Randomizer#106]
**Is your feature request related to a problem? Please describe.**
The SD rando tracker has a button that lets you see at an immediate glance all of the entrances shuffled by the chosen settings. Hovering the cursor over an undiscovered entrance displays the items logically required to access that entrance, while hovering over a discovered entrance shows where that entrance leads to. Undiscovered entrances that are unaccessible are written in red, accessible undiscovered entrances are in blue, and discovered entrances are crossed out.

The HD rando tracker does not have this feature, forcing the player to click on individual island sectors, then the selected island's entrance list to see what leads where. This isn't impossible but it's rather inconvenient, especially considering that HD rando lets you shuffle more entrance types than SD rando.

**Describe the solution you'd like**
Port the SD tracker's button for seeing all entrances and the associated functionality to the HD tracker. This would make navigating seeds with shuffled entrances much easier.

I'm assuming the logical item requirement tooltips for undiscovered entrances would be the hardest part, particularly for the entrances that don't exist in the SD tracker. Hopefully it would still be possible to do, even if it would require some more time. Being able to at the very least see the destination tooltips for discovered entrances would already be a big help by itself.

**Additional context**
I think I saw someone in the randomizer Discord server also suggesting this enhancement, so that prompted me to make this issue about it because I agree that it would be a good thing to add.

**Comment by gymnast86** [comment]
This has been implemented in #110
