### ISSUE TITLE
Location Crashes - Helmaroc King Arena and Dragon Roost Cavern Peak

### ISSUE THREAD

**Issue by apfairfaxgames** [SuperDude88/TWWHD-Randomizer#119]
**Describe the bug**
Two crashes upon entering certain dungeon rooms:
**Dragon Roost Cavern:** Game crashes upon entering the peak Dragon Roost Cavern exterior where Medli is typically held.
The entry in question:
![050](https://github.com/user-attachments/assets/bf8dc851-af3f-4d7a-bd98-6c894feb0f02)
The location I cannot enter due to the crash:
![051](https://github.com/user-attachments/assets/7c47b2fc-28aa-4f16-9858-e4248fcb380e)
**Forsaken Fortress:** Game crashes upon entering the Forsaken Fortress prison cells where Aryll is typically held.
The entry in question:
![024-1](https://github.com/user-attachments/assets/b86e1d33-24c6-4379-a832-958b3d6dab8d)
The location I cannot enter due to the crash:
![030](https://github.com/user-attachments/assets/f42ca743-3aa3-44a0-ba8e-4c75bb35c5e8)
**Error printed upon both crashes:**

> There is a problem with the USB storage device.
> 
> Please contact the manufacturer of the device.
> Check the device's manual for contact information.
> 
> Error Code: 160-0105
> ①5.5.6 U ②WUP-101(02) ③FW111834006 ④BCZ0-0220-7373

**Spoiler Log**
The spoiler log for the seed. If you do not have the spoiler log, provide the non-spoiler log instead (it also contains the config for the seed).
[Lenzo Ganon Non-Spoiler Log.txt](https://github.com/user-attachments/files/17956209/Lenzo.Ganon.Non-Spoiler.Log.txt)
[Lenzo Ganon Spoiler Log.txt](https://github.com/user-attachments/files/17956210/Lenzo.Ganon.Spoiler.Log.txt)

**To Reproduce**
For Dragon Roost Cavern:
1. Progress through Dragon Roost Cavern as normal
2. In the room outside of the Boss arena, enter the door across from it
3. The game crashes

For Helmaroc King arena:
1. Progress through Forsaken Fortress as normal
2. Enter the Helmaroc King arena
3. The game crashes
**Expected behavior**
I anticipate being able to enter the Dragon Roost Cavern room where I would need to fight a miniboss, and I anticipate being able to enter the Helmaroc King arena.

**Platform:**
 - Patcher version and platform: Wii U TWWHD Randomizer app: Version 1.0.1
 - Game platform: Wii U, 
 - Game version: Physical disc Copy

**Additional context**
If I were to take a guess, these crashes expect data specific to earlier stages of the game, when the randomizer is at a later state of the game. Dragon Roost Cavern anticipates Medli to be there when she's in the Earth Temple, and the Helmaroc King arena anticipates Aryll to be there when she's at Windfall Island

I apologize for how vague this information is, please let me know if there's more that I can provide!

**Comment by SuperDude88** [comment]
Could you run this homebrew app https://github.com/SuperDude88/WiiUCrashLogDumper/releases/tag/WiiUCrashLogDumper-DumpLatest and send the log labeled `(latest)` + the one before it (assuming you haven't crashed since these two)?

**Comment by apfairfaxgames** [comment]
I hope this helps! I haven't collected crash logs before  so if it doesn't help, lemme know! [86 (Latest).log](https://github.com/user-attachments/files/17962912/86.Latest.log)

**Comment by SuperDude88** [comment]
This looks like some kind of data corruption (`FSA: ### DATA CORRUPTION ERROR ###, dev:usb01, err:-1245211, cmd:11, path:(null)`), not sure exactly what may have caused it. If the vanilla game works fine in those places, might be worth trying some combination of:
- rerunning the patcher (with the same settings/seed, if you still want to complete that run)
- deleting the randomizer channel via data management (in system settings), then patching to redo first time setup
- installing on a different USB stick 

Before all that I'd check if there's an `Error Log.txt` in the rando app's save folder (the specific path on the SD card is on the `About` page of the homebrew app), if there is one it might offer a little bit of info.

**Comment by apfairfaxgames** [comment]
Deleting the randomizer channel worked, and I was able to access both locations! Thank you so much!
