### ISSUE TITLE
Short Side Quests should skip Lenzo and Minenco

### ISSUE THREAD

**Issue by Crain-32** [SuperDude88/TWWHD-Randomizer#52]
Lenzo and Minenco talking to each other are not currently skipped.

SD doesn't skip them either, but in a racing context we typically clip in during the day and haven't talked with him, which automatically causes that cutscene to not happen.

Since the only clip I know of in HD would be terrible to perform (Sidehop Leaf Pull Ledge Grab -> Roll Clip, thank you Trog), it would be a solid QoL improvement to remove it.

**Comment by SuperDude88** [comment]
Generally going to keep the location categories consistent with SD, but with individual excluded locations this can also be achieved now anyways (#107)
