### ISSUE TITLE
[Patcher Bug] Seed differences between PC and console

### ISSUE THREAD

**Issue by Ammako** [SuperDude88/TWWHD-Randomizer#89]
**Describe the bug**
PC and console give a different seed hash for the same seed.

**Spoiler Log**
N/A

**To Reproduce**
1. Generate a seed on console
2. Manually enter the same seed on PC

**Expected behavior**
PC and console should give the same results for any given seed.

**Screenshots**
![image](https://github.com/SuperDude88/TWWHD-Randomizer/assets/108308111/0b0e5c5c-b6ca-4808-84de-4acb278e7eaf)

**Platform:**
 - 573150e, PC & console

**Additional context**
I haven't checked if this results in different item randomization on PC than on console, but I would expect console and PC players to be able to share seeds and ensure they will all get the same results (important for racing, especially.)

**Comment by SuperDude88** [comment]
The permalinks in both images look quite different towards the middle/end, so the settings are probably different between the two. The seed hash depends on both the seed string and all the settings chosen so without those matched it is expected to be different.
